# Generated by Django 5.2b1 on 2025-03-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceTypes',
            new_name='TypesOfService',
        ),
    ]
