# Generated by Django 5.2b1 on 2025-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_order_description_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('0', 'Наличные'), ('1', 'Банковская карта')], max_length=1),
        ),
    ]
