# Generated by Django 5.2b1 on 2025-03-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
