# Generated by Django 5.2b1 on 2025-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Новая'), ('1', 'В работе'), ('2', 'Выполнено'), ('3', 'Отменено')], default='0', max_length=1),
        ),
    ]
